### ISSUE TITLE
Process_LaTeX on windows machine

### ISSUE THREAD

**Issue by jotelha** [Engineero/Process_LaTeX#1]
Hello,

yesterday I modified your server-side script a bit, as to make it run on my windows machine.
Maybe you want to include this, it appears to work fine on my machine (Win 8) with the following packages installed:

XAMPP for Windows 5.6.14
MiKTeX 2.9  
Strawberry Perl (64-bit) 5.22.0.1  
ImageMagick-6.9.2-Q16               

Their executables must be in the windows search path, and only the local temporary directory "Process_LaTeX/temporary" is used. Paths are specified relative to the "Process_LaTeX" directory.

All the best,

jlh

[process_latex.zip](https://github.com/Engineero/Process_LaTeX/files/260832/process_latex.zip)

**Comment by Engineero** [comment]
That's great, thanks! Do you want to make a pull request with the changes? Then I can incorporate it into the repo.

**Comment by Engineero** [comment]
@jotelha did you happen to see my last comment? If you could create a pull requests with the changes, I can incorporate them into the repo. Thanks a lot!

**Comment by Engineero** [comment]
Closed after merging pull request into main repository.
