### ISSUE TITLE
would you like to add a docker branch?

### ISSUE THREAD

**Issue by trim21** [Engineero/Process_LaTeX#3]
I'm a centos and texlive user, so i edit some code, and write a dockerfile. would you like my to make a Pull requests for a new docker branch?

**Comment by Engineero** [comment]
@Trim21 That would be great if you wanted to do that! Thanks!

**Comment by trim21** [comment]
And, I havn't test it if it can run with windows and MiKTeX, so i think I shouldn't merge it with master branch. It seems that i can only make a pull requests to docker branch after you create and push it manually....

**Comment by Engineero** [comment]
@Trim21 thanks for pointing that out. I added a docker branch. I will see if there is a way to set this up to be easier for collaborators in the future.

**Comment by Engineero** [comment]
@Trim21 would you mind including some instructions in the README to get this up and running? Then I can test it out and close the issue. Thanks!

**Comment by trim21** [comment]
i'll add it later
